version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patientdb-mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  # opcional, só se quiser acessar pelo host
    networks:
      - patient-network
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patient-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PatientManagementDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;"
    networks:
      - patient-network
    ports:
      - "8080:8080"
      - "8081:8081"

volumes:
  mssql-data:

networks:
  patient-network:
    driver: bridge
